# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# XDG Desktop Portal
windowrule {
    name = xdg-portal-gtk
    match:class = (.*xdg-desktop-portal-gtk.*)
    float = true
    center = true
}

# XWayland video bridge
windowrule {
    name = xwaylandvideobridge
    match:class = (.*xwaylandvideobridge.*)
    opacity = 0.0 override 0.0 override
}
