$background = rgba(303446ff)

$error = rgba(e78284ff)

$error_container = rgba(414559ff)

$inverse_on_surface = rgba(303446ff)

$inverse_primary = rgba(303446ff)

$inverse_surface = rgba(c6d0f5ff)

$on_background = rgba(c6d0f5ff)

$on_error = rgba(303446ff)

$on_error_container = rgba(f2d5cfff)

$on_primary = rgba(303446ff)

$on_primary_container = rgba(f2d5cfff)

$on_primary_fixed = rgba(232634ff)

$on_primary_fixed_variant = rgba(414559ff)

$on_secondary = rgba(303446ff)

$on_secondary_container = rgba(f2d5cfff)

$on_secondary_fixed = rgba(232634ff)

$on_secondary_fixed_variant = rgba(414559ff)

$on_surface = rgba(c6d0f5ff)

$on_surface_variant = rgba(b5bfe2ff)

$on_tertiary = rgba(303446ff)

$on_tertiary_container = rgba(f2d5cfff)

$on_tertiary_fixed = rgba(232634ff)

$on_tertiary_fixed_variant = rgba(414559ff)

$outline = rgba(838ba7ff)

$outline_variant = rgba(626880ff)

$primary = rgba(ca9ee6ff)

$primary_container = rgba(414559ff)

$primary_fixed = rgba(babbf1ff)

$primary_fixed_dim = rgba(ca9ee6ff)

$scrim = rgba(000000ff)

$secondary = rgba(f4b8e4ff)

$secondary_container = rgba(414559ff)

$secondary_fixed = rgba(eebebeff)

$secondary_fixed_dim = rgba(f4b8e4ff)

$shadow = rgba(000000ff)

$source_color = rgba(ca9ee6ff)

$surface = rgba(303446ff)

$surface_bright = rgba(51576dff)

$surface_container = rgba(414559ff)

$surface_container_high = rgba(51576dff)

$surface_container_highest = rgba(626880ff)

$surface_container_low = rgba(292c3cff)

$surface_container_lowest = rgba(232634ff)

$surface_dim = rgba(303446ff)

$surface_tint = rgba(ca9ee6ff)

$surface_variant = rgba(51576dff)

$tertiary = rgba(a6d189ff)

$tertiary_container = rgba(414559ff)

$tertiary_fixed = rgba(81c8beff)

$tertiary_fixed_dim = rgba(a6d189ff)
