$background = rgba(1e1e2eff)

$error = rgba(f38ba8ff)

$error_container = rgba(313244ff)

$inverse_on_surface = rgba(1e1e2eff)

$inverse_primary = rgba(1e1e2eff)

$inverse_surface = rgba(cdd6f4ff)

$on_background = rgba(cdd6f4ff)

$on_error = rgba(1e1e2eff)

$on_error_container = rgba(f5e0dcff)

$on_primary = rgba(1e1e2eff)

$on_primary_container = rgba(f5e0dcff)

$on_primary_fixed = rgba(11111bff)

$on_primary_fixed_variant = rgba(313244ff)

$on_secondary = rgba(1e1e2eff)

$on_secondary_container = rgba(f5e0dcff)

$on_secondary_fixed = rgba(11111bff)

$on_secondary_fixed_variant = rgba(313244ff)

$on_surface = rgba(cdd6f4ff)

$on_surface_variant = rgba(bac2deff)

$on_tertiary = rgba(1e1e2eff)

$on_tertiary_container = rgba(f5e0dcff)

$on_tertiary_fixed = rgba(11111bff)

$on_tertiary_fixed_variant = rgba(313244ff)

$outline = rgba(7f849cff)

$outline_variant = rgba(585b70ff)

$primary = rgba(cba6f7ff)

$primary_container = rgba(313244ff)

$primary_fixed = rgba(b4befeff)

$primary_fixed_dim = rgba(cba6f7ff)

$scrim = rgba(000000ff)

$secondary = rgba(f5c2e7ff)

$secondary_container = rgba(313244ff)

$secondary_fixed = rgba(f2cdcdff)

$secondary_fixed_dim = rgba(f5c2e7ff)

$shadow = rgba(000000ff)

$source_color = rgba(cba6f7ff)

$surface = rgba(1e1e2eff)

$surface_bright = rgba(45475aff)

$surface_container = rgba(313244ff)

$surface_container_high = rgba(45475aff)

$surface_container_highest = rgba(585b70ff)

$surface_container_low = rgba(181825ff)

$surface_container_lowest = rgba(11111bff)

$surface_dim = rgba(1e1e2eff)

$surface_tint = rgba(cba6f7ff)

$surface_variant = rgba(45475aff)

$tertiary = rgba(a6e3a1ff)

$tertiary_container = rgba(313244ff)

$tertiary_fixed = rgba(94e2d5ff)

$tertiary_fixed_dim = rgba(a6e3a1ff)
