$background = rgba(eff1f5ff)

$error = rgba(d20f39ff)

$error_container = rgba(ccd0daff)

$inverse_on_surface = rgba(eff1f5ff)

$inverse_primary = rgba(eff1f5ff)

$inverse_surface = rgba(4c4f69ff)

$on_background = rgba(4c4f69ff)

$on_error = rgba(eff1f5ff)

$on_error_container = rgba(dc8a78ff)

$on_primary = rgba(eff1f5ff)

$on_primary_container = rgba(dc8a78ff)

$on_primary_fixed = rgba(dce0e8ff)

$on_primary_fixed_variant = rgba(ccd0daff)

$on_secondary = rgba(eff1f5ff)

$on_secondary_container = rgba(dc8a78ff)

$on_secondary_fixed = rgba(dce0e8ff)

$on_secondary_fixed_variant = rgba(ccd0daff)

$on_surface = rgba(4c4f69ff)

$on_surface_variant = rgba(5c5f77ff)

$on_tertiary = rgba(eff1f5ff)

$on_tertiary_container = rgba(dc8a78ff)

$on_tertiary_fixed = rgba(dce0e8ff)

$on_tertiary_fixed_variant = rgba(ccd0daff)

$outline = rgba(8c8fa1ff)

$outline_variant = rgba(acb0beff)

$primary = rgba(8839efff)

$primary_container = rgba(ccd0daff)

$primary_fixed = rgba(7287fdff)

$primary_fixed_dim = rgba(8839efff)

$scrim = rgba(000000ff)

$secondary = rgba(ea76cbff)

$secondary_container = rgba(ccd0daff)

$secondary_fixed = rgba(dd7878ff)

$secondary_fixed_dim = rgba(ea76cbff)

$shadow = rgba(000000ff)

$source_color = rgba(8839efff)

$surface = rgba(eff1f5ff)

$surface_bright = rgba(bcc0ccff)

$surface_container = rgba(ccd0daff)

$surface_container_high = rgba(bcc0ccff)

$surface_container_highest = rgba(acb0beff)

$surface_container_low = rgba(e6e9efff)

$surface_container_lowest = rgba(dce0e8ff)

$surface_dim = rgba(eff1f5ff)

$surface_tint = rgba(8839efff)

$surface_variant = rgba(bcc0ccff)

$tertiary = rgba(40a02bff)

$tertiary_container = rgba(ccd0daff)

$tertiary_fixed = rgba(179299ff)

$tertiary_fixed_dim = rgba(40a02bff)
