[colors]
primary = {
  background = "#222124"
  foreground = "#FBF7EA"

  normal = {
    black =   "#48474B"
    red =     "#191823"
    green =   "#2B2C3B"
    yellow =  "#534643"
    blue =    "#4C536B"
    magenta = "#9F7563"
    cyan =    "#B7AD93"
    white =   "#F1EBD9"
  }

  bright = {
    black =   "#A9A498"
    red =     "#21202F"
    green =   "#3A3A4E"
    yellow =  "#6E5E59"
    blue =    "#666F8F"
    magenta = "#D49C84"
    cyan =    "#F4E7C4"
    white =   "#F1EBD9"
  }
}

[cursor]
text = "#48474B"
cursor = "#FBF7EA"

[selection]
text = "#48474B"
background = "#666F8F"
