# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in ml4w.conf

# Firefox hardware video decoding (VAAPI on NVIDIA)
env = MOZ_DISABLE_RDD_SANDBOX,1
